export const VETO_SLASHER_ABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "vaultFactory",
        type: "address",
        internalType: "address",
      },
      {
        name: "networkMiddlewareService",
        type: "address",
        internalType: "address",
      },
      {
        name: "networkRegistry",
        type: "address",
        internalType: "address",
      },
      {
        name: "slasherFactory",
        type: "address",
        internalType: "address",
      },
      { name: "entityType", type: "uint64", internalType: "uint64" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BURNER_GAS_LIMIT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BURNER_RESERVE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FACTORY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "NETWORK_MIDDLEWARE_SERVICE",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "NETWORK_REGISTRY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TYPE",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VAULT_FACTORY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cumulativeSlash",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cumulativeSlashAt",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
      { name: "timestamp", type: "uint48", internalType: "uint48" },
      { name: "hint", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeSlash",
    inputs: [
      { name: "slashIndex", type: "uint256", internalType: "uint256" },
      { name: "hints", type: "bytes", internalType: "bytes" },
    ],
    outputs: [
      {
        name: "slashedAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "data", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isBurnerHook",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestSlashedCaptureTimestamp",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "value", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestSlash",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      {
        name: "captureTimestamp",
        type: "uint48",
        internalType: "uint48",
      },
      { name: "hints", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "slashIndex", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolver",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "hint", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolverAt",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "timestamp", type: "uint48", internalType: "uint48" },
      { name: "hint", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolverSetEpochsDelay",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setResolver",
    inputs: [
      { name: "identifier", type: "uint96", internalType: "uint96" },
      { name: "resolver_", type: "address", internalType: "address" },
      { name: "hints", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "slashRequests",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      {
        name: "captureTimestamp",
        type: "uint48",
        internalType: "uint48",
      },
      { name: "vetoDeadline", type: "uint48", internalType: "uint48" },
      { name: "completed", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slashRequestsLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slashableStake",
    inputs: [
      { name: "subnetwork", type: "bytes32", internalType: "bytes32" },
      { name: "operator", type: "address", internalType: "address" },
      {
        name: "captureTimestamp",
        type: "uint48",
        internalType: "uint48",
      },
      { name: "hints", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staticDelegateCall",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vetoDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vetoSlash",
    inputs: [
      { name: "slashIndex", type: "uint256", internalType: "uint256" },
      { name: "hints", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ExecuteSlash",
    inputs: [
      {
        name: "slashIndex",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "slashedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestSlash",
    inputs: [
      {
        name: "slashIndex",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "subnetwork",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "operator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "slashAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "captureTimestamp",
        type: "uint48",
        indexed: false,
        internalType: "uint48",
      },
      {
        name: "vetoDeadline",
        type: "uint48",
        indexed: false,
        internalType: "uint48",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetResolver",
    inputs: [
      {
        name: "subnetwork",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "resolver",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VetoSlash",
    inputs: [
      {
        name: "slashIndex",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "resolver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadySet", inputs: [] },
  { type: "error", name: "CheckpointUnorderedInsertion", inputs: [] },
  { type: "error", name: "InsufficientBurnerGas", inputs: [] },
  { type: "error", name: "InsufficientSlash", inputs: [] },
  { type: "error", name: "InvalidCaptureTimestamp", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "InvalidResolverSetEpochsDelay", inputs: [] },
  { type: "error", name: "InvalidVetoDuration", inputs: [] },
  { type: "error", name: "NoBurner", inputs: [] },
  { type: "error", name: "NoResolver", inputs: [] },
  { type: "error", name: "NotInitialized", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "NotNetwork", inputs: [] },
  { type: "error", name: "NotNetworkMiddleware", inputs: [] },
  { type: "error", name: "NotResolver", inputs: [] },
  { type: "error", name: "NotVault", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8", internalType: "uint8" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "SlashPeriodEnded", inputs: [] },
  { type: "error", name: "SlashRequestCompleted", inputs: [] },
  { type: "error", name: "SlashRequestNotExist", inputs: [] },
  { type: "error", name: "VetoPeriodEnded", inputs: [] },
  { type: "error", name: "VetoPeriodNotEnded", inputs: [] },
];
