name: Test

on:
  push:
    branches:
      - staging
      - main
  pull_request:
  workflow_dispatch:
env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-tags:
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{ steps.check-git-ref.outputs.git_ref }}
      git_branch: ${{ steps.check-git-ref.outputs.git_branch }}
      git_target_branch: ${{ steps.check-git-ref.outputs.git_target_branch }}
    steps:
      - name: Check git ref
        id: check-git-ref
        # if PR
        # else if manual PR
        # else (push)
        run: |
          if [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
            echo "git_branch=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_OUTPUT
            echo "git_target_branch=$(echo ${GITHUB_BASE_REF})" >> $GITHUB_OUTPUT
            echo "git_ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "git_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
            echo "git_target_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
            echo "git_ref=$GITHUB_REF" >> $GITHUB_OUTPUT
          fi
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      solidity_changed: ${{ steps.filter.outputs.solidity }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            solidity:
              - '**/*.sol' # Match any file ending in .sol anywhere in the repo

  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    env:
      # Safe to put here since they are default anvil private keys
      ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
      SEPOLIA_RPC_URL: ${{ secrets.ETH_SEPOLIA_URL }}
      OWNER_PRIVATE_KEY: "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
      NETWORK_PRIVATE_KEY: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
      RESOLVER_PRIVATE_KEY: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
      OPERATOR_PRIVATE_KEY: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"

    needs: [set-tags, detect-changes] # Add detect-changes dependency
    # Only run this job if the 'solidity' filter from detect-changes job is true
    if: needs.detect-changes.outputs.solidity_changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: |
          forge --version

      - name: Install dependencies
        run: |
          make install-tanssi-relayer

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build
